backend = "glx";
#backend = "xrender";

# global
vsync = true;
#################################

# radius
#################################

corner-radius = 10;

# blur
#################################

blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;

# opacity
#################################

rules = (
  {
    match = "class_g = 'kitty'";
    opacity = 0.70;
  },
  {
    match = "class_g = 'Polybar'";
    opacity = 0.70;
  },
  {
    match = "class_g = 'Dunst'";
    opacity = 0.70;
  },
  {
    match = "class_g = 'Rofi'";
    opacity = 0.70;
  }
);
